### ISSUE TITLE
TrainingArguments打印出错

### ISSUE THREAD

**Issue by evanweiguohua** [ssbuild/baichuan_finetuning#1]
------------------config/main.py--------------------
enable_deepspeed = True
enable_ptv2 = False
enable_lora = True
load_in_bit = 0  # 4 load_in_4bit, 8 load_in_8bit  other  0
------------------config/deepspeed_offload.json--------------------

   "optimizer": {
      "type": "AdamW",
      "params": {
        "lr": 2e-5,
        "betas": [0.9, 0.999],
        "eps": 1e-8,
        "weight_decay": 0
      }
   },
--------------------------------------
trian.py打印超参貌似有问题TrainingArguments(optimizer='lion', optimizer_args=None, scheduler_type='linear', scheduler=None, 
大佬修复一下吧！

**Comment by ssbuild** [comment]
https://github.com/ssbuild/baichuan2_finetuning/blob/2edd4b3b7a76ee07a2bcf821a0f0e7cac4309aaa/config/main.py#L87
