### ISSUE TITLE
为什么推理的时候是混乱的结果啊?

### ISSUE THREAD

**Issue by fireinwind** [ssbuild/baichuan_finetuning#16]
采用baichuanV1的13B-Chat模型.
简单修改了一下模型的路径,利用默认的Lora方式做了训练
直接推理demo就是混乱的,这个是怎么回事啊?
input 从南京到上海的路线
output ， ， ， ， ， ， ， ， ， ， ， ， ， 冷， ， ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， ， 把 ， ， 把 ， 把 ， 把 ， ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， ， 把 ， 把 ， ， 把 ， 把 ， ， 把 ， 把 ， 把 ， ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， ， 把 ， 把 ， 把 ， 把 ， 把

**Comment by ssbuild** [comment]
默认的参数和数据，基本上跑10轮左右就可以拟合。 观察自己的loss 调参
