### ISSUE TITLE
deep_train 跟torchversion版本有兼容性问题么？

### ISSUE THREAD

**Issue by qingyuan18** [ssbuild/baichuan_finetuning#2]
/opt/conda/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or director
/opt/conda/lib/python3.9/site-packages/lightning/pytorch/callbacks/callback. │
│ py:22 in <module>    

方便告知一下deep_train用的ligtning，torchversion，pytorch分别需要什么版本吗？
用git源代码方式install，在如下版本的算力机器上直接报torchversion的错：
huggingface-pytorch-training:1.13.1-transformers4.26.0-gpu-py39-cu117-ubuntu20.04

transformers和其他lib都已经按这上面的requriments install升级过了

谢谢

**Comment by ssbuild** [comment]
没有兼容性问题吧， 看你这个错误是 torchvision 找不到cuda ， 建议 新建个环境安装对应的torch 和 torchvision ，这俩对cuda 有依赖。

**Comment by qingyuan18** [comment]
环境都是一样的，chatglm/vicuna都是用的同样的算力机，torch和torchvision如果有不匹配，之前的fine tune肯定都会报

https://github.com/hiyouga/LLaMA-Efficient-Tuning.git 换这个repo来fine tune baichuan是可以正常运行的

**Comment by ssbuild** [comment]
上传下错误信息。
