### ISSUE TITLE
请问，如何要使baichuan-13B的lora支持peft调用，权重该如何修改，感激！！

### ISSUE THREAD

**Issue by yuymf** [ssbuild/baichuan_finetuning#2]

**Comment by ssbuild** [comment]
训练的lora权重， peft 调用？ https://github.com/ssbuild/baichuan2_finetuning/blob/dev/convert_lora_to_peft.py

**Comment by yuymf** [comment]
修改了两处代码报错，可以运行[convert_lora_to_peft.py](https://github.com/ssbuild/baichuan2_finetuning/blob/dev/convert_lora_to_peft.py)
1.`from aigc_zoo.model_zoo.baichuan2.llm_model import LoraModel`
2.`peft_config = LoraConfig(
       ...
        target_modules=lora_args.target_modules,
    )`
 但是产生的peft_lora无法得到之前lora权重的效果，

![image](https://github.com/ssbuild/baichuan2_finetuning/assets/60524184/76651afb-9bdc-44d7-ba75-682189dcc7bd)

想问一下大佬如何解决？感谢orz

**Comment by ssbuild** [comment]
感谢反馈，新脚本已测试通过  , try.

**Comment by yuymf** [comment]
感谢，俺也测试通过了！：）
