### ISSUE TITLE
请教：AttributeError: 'DistributedDataParallel' object has no attribute 'compute_loss'

### ISSUE THREAD

**Issue by quzx** [ssbuild/baichuan_finetuning#35]
前序环节正常，但是总在   trainer_hf.py执行到
train_result = trainer.train(resume_from_checkpoint=checkpoint)  报错：
AttributeError: 'DistributedDataParallel' object has no attribute 'compute_loss'
直接python trainer_hf.py        
或者CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=1 train_hf.py
       CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 train_hf.py   都是的。
48G*2块显卡
python 3.10.12
启用   不启用deepspeed都是的。   baichuan-13b-chat, lora, huggingface
可否帮着分析一下？谢谢

**Comment by quzx** [comment]
bug?

**Comment by ssbuild** [comment]
> bug?

是的，单卡应该可以，多卡被外面还有一层，所以找不到函数，deep_training 0.2.5.post2 已修复。

**Comment by quzx** [comment]
单机，双卡，更新后再次  分别  运行：
torchrun --nproc_per_node=1 train_hf.py   
torchrun --nproc_per_node=2 train_hf.py   
deepspeed  --num_gpus 2 train_hf.py 
都得到相同错误提示：
[INFO|trainer.py:1712] 2023-10-09 22:23:34,408 >> ***** Running training *****
[INFO|trainer.py:1713] 2023-10-09 22:23:34,408 >>   Num examples = 362
[INFO|trainer.py:1714] 2023-10-09 22:23:34,408 >>   Num Epochs = 10
[INFO|trainer.py:1715] 2023-10-09 22:23:34,408 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1718] 2023-10-09 22:23:34,408 >>   Total train batch size (w. parallel, distributed & accumulation) = 2
[INFO|trainer.py:1719] 2023-10-09 22:23:34,408 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1720] 2023-10-09 22:23:34,408 >>   Total optimization steps = 1,810
[INFO|trainer.py:1721] 2023-10-09 22:23:34,410 >>   Number of trainable parameters = 6,553,600
  0%|                                                                                                                            | 0/1810 [00:00<?, ?it/s]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
  File "/home/qqq/llama2/baichuan_finetuning/train_hf.py", line 191, in <module>
    main()
  File "/home/qqq/llama2/baichuan_finetuning/train_hf.py", line 173, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/transformers/trainer.py", line 2690, in training_step
    self.accelerator.backward(loss)
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/accelerate/accelerator.py", line 1983, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/qqq/anaconda3/envs/qwenf/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 79 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

**Comment by ssbuild** [comment]
train_info_args_hf 配置 gradient_checkpointing  = False ， 试试

**Comment by quzx** [comment]
修改了，还是相同错误信息。
有群交流吗？效率高一点

**Comment by ssbuild** [comment]
> 修改了，还是相同错误信息。 有群交流吗？效率高一点

已经修复，  群: 185144988
